config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'home#index'

	resources :users
	get '/user', to: "users#show"
	get '/user/edit', to: "users#edit"
	patch '/user/update', to: "users#update"
	delete '/user/delete', to: "users#destroy"

	resources :persons

	# get '/person', to: "persons#show"
	# get '/person/edit', to: "persons#edit"
	get '/person_list/clear', to: "persons#clear"
	get '/person_list/seed', to: "persons#seed_faked"
	# patch '/person/update', to: "persons#update"
	# delete '/person/delete', to: "persons#destroy"


	# post '/persons/save', to: "persons#write_to_session"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person

	attr_reader :id
	attr_accessor :fullname, :email, :contacts

	def initialize(id = nil, fullname = '', email = '', contacts = '')
		@id, @fullname, @email, @contacts = id, fullname, email, contacts
	end

	def to_h
		{id: @id, fullname: @fullname, email: @email, contacts: @contacts}
	end

end

app/models/person_factory.rb
class PersonFactory

	def initialize max_id
		@max_id = max_id
	end

	def build_person
		new_person = Person.new(next_id)
	end

	def build_fake_person_list qty
		persons = Array.new
		qty.times do |i|
			fake_person_id = next_id + i
			persons << Person.new(
				fake_person_id, 
				"fullname#{fake_person_id}",
				"email#{fake_person_id}",
				"contacts#{fake_person_id}"
				)
		end
		persons
	end

	private

	def next_id
		@max_id + 1
	end

end

app/models/person_file_store.rb
class PersonFileStore
	
	PERSONS_FILE_PATH = "#{Rails.root.to_s}/tmp/persons.json"

	def initialize
		unless File.file?(PERSONS_FILE_PATH) 
			File.open(PERSONS_FILE_PATH, "w") {|f| f << {}.to_json}
		end
	end

#{1: {id: 1, name: 'Anton'}, 2: {id: 2, name: 'Lena'}, 3: {id: 3, name: 'Vasya'}}

	def read
		result = {}
		persons_json = File.read(PERSONS_FILE_PATH)
		persons = JSON.parse(persons_json)
		persons.each_key do |id|
			person = persons[id]
			person = person.with_indifferent_access
			result[person[:id]] = Person.new(person[:id], person[:fullname], person[:email], person[:contacts])
		end
		result
	end

	#{1: Person(id: 1, name: 'Anton'), 2: Person(id: 2, name: 'Lena'), 3: Person(id: 3, name: 'Vasya')}
	
	def write(persons)
		result = {}
		persons.each_key do |id|
			result[id] = persons[id].to_h
		end
		File.open(PERSONS_FILE_PATH, "w") do |f|
			f << result.to_json
		end
	end

end

app/models/person_manager.rb
class PersonManager

	def initialize store
		@store = store
		@persons = store.read
	end

	def save_persons
		@store.write(@persons)
	end

	def add(person)
		@persons[person.id] = person
	end

	def remove(id)
		@persons.delete(id)
	end

	def persons
		@persons.dup
	end

	def find_by_id(id)
		@persons[id]
	end

	def max_id
		@persons.keys.max || 0
	end
end

app/models/person_session_store.rb
class PersonSessionStore

	def initialize session
		@session = session
	end

	#{1: {id: 1, name: 'Anton'}, 2: {id: 2, name: 'Lena'}, 3: {id: 3, name: 'Vasya'}}

	def read
		result = {}
		persons = @session[:persons] || {}
		persons.each_key do |id|
			person = persons[id]
			person = person.with_indifferent_access
			result[person[:id]] = Person.new(person[:id], person[:fullname], person[:email], person[:contacts])
		end
		result
	end

	#{1: Person(id: 1, name: 'Anton'), 2: Person(id: 2, name: 'Lena'), 3: Person(id: 3, name: 'Vasya')}
	
	def write(persons)
		result = {}
		persons.each_key do |id|
			result[id] = persons[id].to_h
		end
		@session[:persons] = result
	end

end

app/models/user.rb
class User

	attr_reader :fullname, :email, :contacts

	def initialize(fullname, email, contacts)
		@fullname, @email, @contacts = fullname, email, contacts
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end
	
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

	before_action :set_person_manager
	before_action :person_params, only: [:create, :destroy, :update]
	before_action :set_person, only: [:show, :edit, :update]

	def index
		@persons = @person_manager.persons
	end

	def new
		@person = Person.new
	end

	def create
		person = @person_factory.build_person
	    if person
			person.fullname = params[:fullname]
			person.email = params[:email]
			person.contacts = params[:contacts]
			@person_manager.add(person)
	      	@person_manager.save_persons
	      	redirect_to action: 'index'
	    else
	      	flash[:danger] = "Smth went wrong (((" 
	      	render 'new'
	    end
	end

	def show
	end

	def edit
	end

	def update
		@person.fullname = params[:fullname]
		@person.email = params[:email]
		@person.contacts = params[:contacts]
		@person_manager.save_persons
		redirect_to action: 'show'
	end

	def destroy
		@person_manager.remove(params[:id].to_i)
		@person_manager.save_persons
		redirect_to action: 'index'
	end

	def clear
		File.open(PersonFileStore::PERSONS_FILE_PATH, "w") {|f| f << {}.to_json}
		redirect_to action: 'index'
	end

	def seed_faked
		faked_persons = @person_factory.build_fake_person_list 5
		faked_persons.each{|person| @person_manager.add(person)}
		@person_manager.save_persons
		redirect_to action: 'index'
	end

	private

	def set_person_manager
		@person_manager = PersonManager.new(PersonFileStore.new())
		# @person_manager = PersonManager.new(PersonSessionStore.new(session))
		@person_factory = PersonFactory.new(@person_manager.max_id)
	end

	def set_person
		@person = @person_manager.find_by_id(params[:id].to_i)
	end

	def person_params
		params.permit([:id, :fullname, :email, :contacts])
	end
	
end

app/controllers/users_controller.rb
require "ostruct"

class UsersController < ApplicationController

	def index
		@users = fake_users
	end

	def new
	  	@user = OpenStruct.new(:fullname => '', :email => '', :contacts => '')
	end

	def create
		@user = make_user
		@users = fake_users
		@users.push(@user)
	    if @user
	      render 'index'
	    else
	      flash[:danger] = "Smth went wrong (((" 
	      render 'new'
	    end
	end

	def show
		@user = make_user
	end

	def edit
		@user = make_user
	end

	def update
		@user = make_user
		if @user
			render 'show'
		end
	end

	def destroy
		@user = make_user
		@users = fake_users
		@users.delete_if{ |i| i.fullname == @user.fullname }
		render 'index'
	end

	private

	def fake_users
		users = Array.new()
		users.push(OpenStruct.new(
			:fullname => 'Иванов Иван Иванович',
			:email => Array.new() << 'ivanov@example.com' << 'ivanov@ivanov.com',
			:contacts => 'contacts1'))
		users.push(OpenStruct.new(
			:fullname => 'Сидоров Сидор Сидорович',
			:email => Array.new() << 'sidorov@example.com',
			:contacts => 'contacts2'))
		users.push(OpenStruct.new(
			:fullname => 'Эйабдурахман-оглы Теймураз Хафиздурмухаммедович',
			:email => Array.new() << 'ogly@example.com',
			:contacts => 'contacts3'))
		users
	end

	def make_user
		OpenStruct.new(
			:fullname => params[:fullname],
			:email => params[:email].split(' ').reject{ |e| e.empty? },
			:contacts => params[:contacts])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hi, all!!!</h1>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="#">Hvs-Fasya.ru</a>
	  </div>
	  <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
	      <%= render 'layouts/navigation_links' %>
        </ul>
      </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<li class='active'><%= link_to 'Home', class: '' %></li>
<li class=''><%= link_to 'Пользователи', users_path, class: '' %></li>
<li class=''><%= link_to 'Персоны', persons_path, class: '' %></li>
<li class=''><%= link_to 'MenuItem3', class: '' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Et</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Styles custom-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
      <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="starter-template">
        <%= yield %>
      </div>
    </div>
     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/persons/_form.html.erb
<%= form_tag( form_action, class: "form-horizontal", method: form_method) do %>
  <div class="form-group">
  	<%= label_tag :fullname, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :fullname, @person.fullname, class: "form-control", placeholder: "Пупкин Петр Семенович"  %>
  	</div>
  </div>
  <div class="form-group">
  	<%= label_tag :email, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :email, @person.email, class: "form-control", :placeholder => "example@example.com, example@example.com"  %>
  	</div>
  </div>
  <div class="form-group">
  	<%= label_tag :contacts, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :contacts, @person.contacts, class: "form-control", :placeholder => "+79031234567" %><br />
  	</div>
  </div>
  <div class="col-sm-offset-4">
    <%= submit_tag 'Save person', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/persons/_person_row.html.erb
<td><%= link_to fa_icon("edit 2x"), "/persons/#{person.id}/edit" %></td>
<td class="table-texts no-wrap"><%= link_to person.fullname, "/persons/#{person.id}" %></td>
<td class="table-texts"><%= person.email %></td>
<td class="table-texts"><%= person.contacts %></td>
<td><%= link_to fa_icon("remove 2x"), "/persons/#{person.id}", method: :delete %></td>

app/views/persons/edit.html.erb
<div class="clearfix">
  <h1 class="inline">Edit Person Here</h1>
</div>
<br>
<%= render partial: "form", person: @person,
  locals: { form_method: :patch, form_action: "/persons/#{@person.id}" } %>

app/views/persons/index.html.erb
<div class="clearfix">
  <h1 class="inline">Persons List</h1>
  <%= link_to fa_icon("plus 3x"), new_person_path(), :class => "btn btn-primary inline pull-right" %>
</div>
<br>
<p class="lead">
  hier sind unsere wertvollen Nutzer
</p>
<%= link_to "Seed 5 Fake Persons", "person_list/seed", :class => "btn btn-primary inline pull-right" %>
<br>
<table class='table table-striped'>
  <tr>
    <th class="table-digits th-5">#</th>
    <th class="th-5"></th>
    <th>Name</th>
    <th class="th-20">E-mail</th>
    <th class="th-20">Contacts</th>
    <th class="th-5"></th>
  </tr>
  <tbody>
  <% @persons.each do |id,person| %>
  <br>
    <tr>
      <td class="table-digits"><%= id %></td>
      <%= render partial: "person_row", locals: {person: person} %>
    </tr>
<% end %>
</tbody>
</table>
<% if !@persons.empty? %>
  <%= link_to "Clear Persons list", "person_list/clear", :class => "btn btn-primary inline pull-right" %>
<% end %>

app/views/persons/new.html.erb
<div class="clearfix">
  <h1 class="inline">Create New Person Here </h1>
  <%= fa_icon("arrow-down 2x", :class => "inline") %>
</div>
<br>
<%= render partial: "form",
 locals: {form_method: "post", form_action: "/persons"} %>

app/views/persons/show.html.erb
<div class="clearfix">
  <h1 class="inline">Person's Data</h1>
</div>
<br>
<table class='table table-inverse'>
  <tbody>
  <tr>
    <%= render partial: "person_row", locals: {person: @person} %>
  </tr>
</tbody>
</table>

app/views/users/_form.html.erb
<%= form_tag( form_action, class: "form-horizontal", method: form_method) do %>
  <div class="form-group">
  	<%= label_tag :fullname, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :fullname, @user.fullname, class: "form-control", placeholder: "Пупкин Петр Семенович"  %>
  	</div>
  </div>
  <div class="form-group">
  	<%= label_tag :email, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :email, @user.email, class: "form-control", :placeholder => "example@example.com, example@example.com"  %>
  	</div>
  </div>
  <div class="form-group">
  	<%= label_tag :contacts, nil, class: "col-sm-offset-1 col-sm-2 control-label" %>
  	<div class="col-sm-6">
  	  <%= text_field_tag :contacts, @user.contacts, class: "form-control", :placeholder => "+79031234567" %><br />
  	</div>
  </div>
  <div class="col-sm-offset-4">
    <%= submit_tag 'Save User', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user_row.html.erb
<td><%= link_to fa_icon("edit 2x"), "/user/edit?#{user.each_pair.to_h.to_query}" %></td>
<td class="table-texts no-wrap"><%= link_to user.fullname, "/user?#{user.each_pair.to_h.to_query}" %></td>
<td class="table-texts"><%= user.email.join(" ") %></td>
<td class="table-texts"><%= user.contacts %></td>
<td><%= link_to fa_icon("remove 2x"), "/user/delete?#{user.each_pair.to_h.to_query}", method: :delete %></td>

app/views/users/edit.html.erb
<div class="clearfix">
  <h1 class="inline">Edit User Here</h1>
</div>
<br>
<%= render partial: "form", user: @user,
  locals: { form_method: :patch, form_action: "/user/update" } %>

app/views/users/index.html.erb
<div class="clearfix">
  <h1 class="inline">Users List</h1>
  <%= link_to fa_icon("plus 3x"), new_user_path(), :class => "btn btn-primary inline pull-right" %>
</div>
<br>
<p class="lead">
  hier sind unsere wertvollen Nutzer
</p>
<table class='table table-striped'>
  <tr>
    <th class="table-digits th-5">#</th>
    <th class="th-5"></th>
    <th>Name</th>
    <th class="th-20">E-mail</th>
    <th class="th-20">Contacts</th>
    <th class="th-5"></th>
  </tr>
  <tbody>
<% @users.each_with_index do |user,i| %>
<br>
  <tr>
    <td class="table-digits"><%= i+1 %></td>
    <%= render partial: "user_row", locals: {user: user} %>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<div class="clearfix">
  <h1 class="inline">Create New User Here </h1>
  <%= fa_icon("arrow-down 2x", :class => "inline") %>
</div>
<br>
<%= render partial: "form",
 locals: {form_method: "post", form_action: "/users"} %>

app/views/users/show.html.erb
<div class="clearfix">
  <h1 class="inline">User's Data</h1>
</div>
<br>
<table class='table table-inverse'>
  <tbody>
  <tr>
    <%= render partial: "user_row", locals: {user: @user} %>
  </tr>
</tbody>
</table>